FROM alpine
EXPOSE 80
RUN apk update && apk add python3
RUN apk add git
RUN git clone https://github.com/PvonK/lab.git
WORKDIR /lab/alumnos/58164-philipp-von-kesselstatt/TrabajoPractico_4/

# RUN pip install -r requirements.txt

# CMD [ "python3" ]